In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pyplot

In [18]:
strike = 0
spot_0 = 50
Time = 0
t = 10/360
Ru = 1.02
Rd = 0.98

In [5]:
alfa = np.zeros((3,3))
alfa[2,1] = 3
alfa

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 3., 0.]])

In [ ]:
def stock_prices(spot_0, Time, Ru, Rd):
    empty_matrix = np.zeros((Time-1, Time-1))

    for i in range(0,Time+1,1):
        empty_matrix[]
    return empty_matrix

In [19]:
Time = 2
empty_matrix = np.zeros((Time+1, Time+1))
empty_matrix[0,0] = spot_0

for i in range(1,Time+1,1):
    for j in range(0,i,1):
        iterator = i +1
        ups = j


        stock_price = spot_0 * Ru**(i-j) + Rd**(j)
        empty_matrix[i,j] = stock_price

In [ ]:
empty_matrix[0,]

array([50.,  0.,  0.])

In [22]:
empty_matrix.T

array([[50.  , 52.  , 53.02],
       [ 0.  ,  0.  , 51.98],
       [ 0.  ,  0.  ,  0.  ]])